<nav>
    <div class = "lien">
        <p> | Fair count |</p>
        <a href="./"> Acceuille </a>
        <a href="<?php if(isset($isConnected) && $isConnected) {
                             ?>  ?route=groupe <?php } 
                        else {
                            ?> ?route=connect <?php }?>"> groupe </a>
    </div>
    <?php if(isset($isConnected) && $isConnected) {
            ?><p class = "name"><?php echo $data["username"]; ?></p><?php
        } else {
            ?> <a class ="connect" href="?route=connect"> se connecter </a> <?php } ?>
    
</nav>