<?php
    $groupe_link = (isset($isConnected) && $isConnected) ? '?route=groupe' : '?route=connect';
    $solde = isset($_SESSION['tune']) ? htmlspecialchars($_SESSION['tune']) . " $" : '0 $';
?>

<nav class="main-nav">
    <div class="nav-brand-links">
        <p class="nav-brand">Fair Count</p>
        <a href="./" class="nav-link">Accueil</a>
        <a href="<?php echo $groupe_link; ?>" class="nav-link">Groupes</a>
    </div>

    <?php if(isset($isConnected) && $isConnected){ ?>
        <div class="nav-user-info">
            <p class="user-tune-display"><?php echo $solde; ?></p>
            <p class="user-name-display"><?php echo htmlspecialchars($data["username"]); ?></p>
            
            <form method="POST" action="index.php?route=auth/unlogin" class="logout-form">
                <button type="submit" class="btn logout-btn">Déconnexion</button>
            </form>
        </div>
    <?php }else{ ?>
        <a class="nav-connect-btn" href="?route=connect">Se connecter</a>
    <?php } ?>
</nav>