

<h1 class = "moulaga"><?= $data["group"]->getBudget() ?></h1>
<p>salut</p>
<?php $code_groupe = $data["group"]->getCode(); ?>

<form method="POST" action="index.php?route=budget/ajouter">
    <h2>Ajouter un montant au budget</h2>
    
    <label for="montant_ajout">Montant à ajouter :</label>
    <input type="number" step="0.01" name="montant_ajout" id="montant_ajout" required>
    
    <input type="hidden" name="code_groupe" value="<?php echo $code_groupe; ?>">
    
    <button type="submit">Ajouter</button>
</form>

<?php $code_groupe = $data["group"]->getCode();?>

<form method="POST" action="index.php?route=budget/retirer">
    <h2>Retirer un montant du budget</h2>
    
    <label for="montant_retrait">Montant à retirer :</label>
    <input type="number" step="0.01" name="montant_retrait" id="montant_retrait" required>
    
    <input type="hidden" name="code_groupe" value="<?php echo $code_groupe; ?>">
    
    <button type="submit">Retirer</button>
</form>

<a class ="connect" href="?route=depense/creer&code=<?php echo htmlspecialchars($code_groupe); ?>"> credepance </a>