<h2 class="groupe_titre"> Créer un nouveau groupe</h2>

<?php if (isset($error) && $error){ ?>
    <p>
        <?= htmlspecialchars($error) ?>
    </p>
<?php } ?>

<form method="POST" action="index.php?route=created_groupv" class="groupe">
    <div>
        <label for="name">Nom du groupe </br></label>
        <input class="groupe_text_zone" type="text" id="name" name="name" required 
               value="<?= $_POST['name'] ?? '' ?>" 
               aria-describedby="nameHelp">
    </div>

    <div>
        <label for="code">Code d'invitation (4-8 caractères)  </br> </label>
        <input class="groupe_text_zone" type="text" id="code" name="code" required minlength="4" maxlength="8"
               value="<?= $_POST['code'] ?? '' ?>"
               aria-describedby="codeHelp">
    </div>
    <button class="group_bouton" type="submit">Créer le groupe</button>
</form>