<h2>Créer un nouveau groupe</h2>

<?php if (isset($error) && $error){ ?>
    <p style="color: red; padding: 10px; border: 1px solid red; background-color: #ffebeb;">
        <?= htmlspecialchars($error) ?>
    </p>
<?php } ?>

<form method="POST" action="index.php?route=created_groupv">
    <div>
        <label for="name">Nom du groupe </br></label>
        <input type="text" id="name" name="name" required 
               value="<?= $_POST['name'] ?? '' ?>" 
               aria-describedby="nameHelp">
        <small id="nameHelp">Exemple : Week-end Ski, Projet Bêta...</small>
    </div>

    <div>
        <label for="code">Code d'invitation (4-8 caractères)  </br> </label>
        <input type="text" id="code" name="code" required minlength="4" maxlength="8"
               value="<?= $_POST['code'] ?? '' ?>"
               aria-describedby="codeHelp">
        <small id="codeHelp">Un code unique que les autres utiliseront pour rejoindre le groupe.</small>
    </div>

    <button class="group_bouton" type="submit">Créer le groupe</button>
</form>