<h1> liste de vos groupe </h1>
<p><?= var_dump($data["groupes"]) ?></p>

<table class = "stats-table">
<thead>
    <tr>
        <th>name</th>
        <th>budget</th>
    </tr>
    <tr>
</thead>
<tbody>
    <?php 

    foreach ($data["groupes"] as $groupe) {
        ?>
        <th><?php echo $groupe->getName(); ?></th>
       
        <th><?php echo $groupe->getbudget();?></th>
         <?php } ?> 
    </tr>
</tbody>    

</table>
<form>
    <button> Rejoindre un groupe </button>
</form>
<form>
    <button> crer un groupe </button>
</form>