<h1> liste de vos groupe </h1>

<table class = "stats-table">
<thead>
    <tr>
        <th>name</th>
        <th>budget</th>
    </tr>
    
</thead>
<tbody>
    <?php 

    foreach ($data["groupes"] as $groupe) {
        ?>
        <tr></tr>
        <th><?php echo $groupe->getName(); ?></th>
       
        <th><?php echo $groupe->getbudget() . " $";?></th>
         <?php } ?> 
         </tr>
    
</tbody>    

</table>
<form method="POST" action="index.php?route=ajoin_group">
    <button> Rejoindre un groupe </button>
</form>
<form method="POST" action="index.php?route=created_group">
    <button> crer un groupe </button>
</form>