<main class="accueil-container">
    <div class="hero-content">
        <h1>Bienvenue sur Fair Count</h1>
        <p id="lead">Gérez et équilibrez vos comptes entre amis facilement et sans stress.</p>

        <div class="slogan-section">
            <h2>VACANCES SANS TRACAS, AMITIÉS SANS SOUCIS.</h2>
            <p>Grâce à Fair Count, mettez fin aux complications financières entre amis.</p>
            <p>Chacun sait exactement ce qu'il a dépensé et ce qu'il doit aux autres.</p>
        </div>
        <?php if(!isset($isConnected) && !$isConnected){ ?>
            <a href="?route=connect" class="cta-button">
                Commencez maintenant, c'est gratuit !
            </a>
        <?php } ?>
    </div>

    <div class="hero-image">
        <img src="assets/image/image_gens_qui_s'amuse.jpg" alt="Un groupe d'amis souriants partageant un moment de joie">
    </div>
</main>