<div>
    <h1>Bienvenue sur Fair Count</h1>
    <p id="lead">Gérez vos comptes entre amis facilement.</p>
</div>
<div id="text_acueille">
    <p> POUR DES VACANCE SANS TRACKA </p>
    <p> grace a fair count pas finit les souci financier entre amis</p>
    <p> chacun sait se qu'il dépense et se qu'il doit au autre </p>
</div>
<div class ="img">
    
    <img src="assets/image/image_gens_qui_s'amuse.jpg" >
</div>