<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <title>Fair Count </title>
</head>
<body>
    <?php
        
        
        
        // Note : $template doit être la variable extraite des données par AbstractController::render()
        require "templates/partials/$template.phtml";
    
    ?>
</body>
</html>