<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <link rel="stylesheet" href="assets/css/style.css">
    <title>Fair Count </title>
</head>
<body>
    <?php
        
        
        require "templates/partials/_nav.phtml";
        require "templates/partials/$template.phtml";
    
    ?>
</body>
</html>