<div class="login">
    
    <h2 class="titr">Connexion</h2>
    
    <?php 
    if (isset($error) && $error){
    ?>
        <div class="alert alert-danger"><?= htmlspecialchars($error) ?></div>
    <?php } ?>
    
    <form method="POST" action="index.php?route=auth/login">
        <div class="inputz">
            <label for="email" class="form-label">Email</label>
            <input type="email" class="form-control" id="email" name="email" required>
        </div>
        <div class="inputz">
            <label for="password" class="form-label">Mot de passe</label>
            <input type="password" class="form-control" id="password" name="password" required>
        </div>
        <button type="submit" class="btn">Se connecter</button>
    </form>
    <p class="mt-3">Pas encore de compte ? <a href="?route=creat">Créer un compte</a></p>

</div>